version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - example_net
  db:
    image: postgres
    volumes:
      - ./tmp/db:/usr/local/var/postgres/postgresql.conf
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - example_net
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/fx_transactions_microservice
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - example_net
networks:
  example_net:
    driver: bridge


#
